name: solar-system
on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop
env:
  MONGO_URI: ${{ vars.MONGO_URI }}
  MONGO_USERNAME: ${{ vars.MONGO_USERNAME }}
  MONGO_PASSWORD: ${{ secrets.MONGO_PASSWORD }}
jobs:
  unit-tests:
    strategy:
      matrix:
        node-version: [22,24]
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    environment: solar-system
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: install npm
        run: npm install
      - name: run unit test
        run: npm test
      - name: upload test results
        if: always()
        uses: actions/upload-artifact@v7.0.1
        with:
          name: test-results
          path: test-results.xml